watch_stylesheet: true
watch_config: true
debug: false
tooltip:
  offset: 6
  blur_effect:
    enabled: true
    dark_mode: true
    round_corners: true
    round_corners_type: "small"
    border_color: "None"
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ['*'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
    blur_effect:
      enabled: false
      dark_mode: true
      round_corners: true
      border_color: transparent
    window_flags:
      always_on_top: true
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 36
    padding:
      top: 0 # 4 4 2 4
      left: 0
      bottom: 0
      right: 0
    widgets:
      left:
        [
          "komorebi_workspaces",
          "komorebi_active_layout",
          "taskbar",
        ]
      center:
        []
      right:
        [
          "cava",
          "media",
          "volume",
          "update_check",
          "clock",
          "systray",
          "wallpapers",
          "power_menu"
        ]
widgets:
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb80\udf5c</span>"
      menu_list:
      - { title: "Home", path: "~" }
      - { title: "Downloads", path: "C:\\Users\\elrond\\Downloads"}
      - { title: "Documents", path: "C:\\Users\\elrond\\Documents"}
      - { title: "Pictures", path: "C:\\Users\\elrond\\Pictures"}
      - { title: "Videos", path: "C:\\Users\\elrond\\Videos"}
      system_menu: true
      power_menu: false
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: ""
      alignment: "left"
      direction: "down"
      menu_labels:
        shutdown: "Shutdown"
        restart: "Restart"
        logout: "Logout"
        lock: "Lock"
        sleep: "Sleep"
        system: "System Settings"
        about: "About This PC"
        task_manager: "Task Manager"
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
        label_offline: "\u26a1 Offline"
        label_workspace_btn: ""
        label_workspace_active_btn: ""
        label_workspace_populated_btn: ""
        label_default_name: "{index}"
        label_zero_index: false
        hide_empty_workspaces: false
        hide_if_offline: true
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "<span>{icon}</span> {location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: 'EnterAPIKeyHere'
      update_interval: 600 #Update interval in seconds, Min 600
      hide_decimal: true
      location: 'Irkutsk'
      callbacks:
        on_left: "toggle_label"
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\udb81\udd99"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\udb81\udd99"
        rainyDay: "\udb81\udd99"
        rainyNight: "\udb81\udd99"
        snowyIcyDay: "\udb81\udd99"
        snowyIcyNight: "\udb81\udd99"
        blizzardDay: "\udb81\udd99"
        default: "\udb81\udd99" 
  media:
      type: "yasb.media.MediaWidget"
      options:
        label: "{artist} - {title}"
        label_alt: "{artist}"
        callbacks:
          on_left: "toggle_media_menu"
          on_middle: "do_nothing"
          on_right: "toggle_label"
        max_field_size:
          label: 45
          label_alt: 45
        show_thumbnail: false
        controls_only: false
        controls_left: true
        hide_empty: true
        thumbnail_alpha: 250
        thumbnail_padding: 8
        thumbnail_corner_radius: 6
        icons:
          prev_track: ""
          next_track: ""
          play: "<span>\uf001</span>"
          pause: "<span>\uf001</span>"
        media_menu:
          blur: true
          round_corners: true
          round_corners_type: "normal"
          border_color: "System"
          alignment: "right"
          direction: "down"
          offset_top: 5
          offset_left: 0
          thumbnail_size: 100
          thumbnail_corner_radius: 6
          max_title_size: 60
          max_artist_size: 50
          show_source: true
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 36
      max_length_ellipsis: "..."
      monitor_exclusive: true
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{level}"
      tooltip: true
      scroll_step: 2
      slider_beep: false

      icons:
        muted: "\ueee8"
        "10": "\uf026"
        "30": "\uf027"
        "60": "\uf027"
        "100": "\uf028"

      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0

        show_apps: true
        show_app_labels: true
        show_app_icons: true
        show_apps_expanded: true

        app_icons:
          toggle_down: "\uf078"
          toggle_up: "\uf077"

      callbacks:
        on_left: "toggle_volume_menu"
        on_middle: "toggle_label"
        on_right: "toggle_mute"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a %b %d %H:%M}"
      label_alt: "{%A, %d %B %Y %H:%M}"
      timezones: []

      calendar:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
  disk:
    type: "yasb.disk.DiskWidget"
    options:
        label: "<span>\uf473</span>"
        label_alt: "<span>\uf473</span>"
        update_interval: 60
        group_label:
          volume_labels: ["C", "D", "E", "F"]
          show_label_name: false
          blur: True
          round_corners: True
          round_corners_type: "small"
          border_color: "System"
          alignment: "right"
          direction: "down"
        callbacks:
          on_left: "toggle_group"
          on_middle: "toggle_label"
          on_right: "exec explorer C:\\" # Open disk C in file explorer
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\udb83\ude09</span>"
      image_path: "C:\\Users\\User\\Downloads\\Wallpapers"
      change_automatically: false
      update_interval: 60

      engine:
        enabled: true
        animation: "slide_top"

      callbacks:
        on_left: "toggle_gallery"
        on_middle: "do_nothing"
        on_right: "change_wallpaper"

      gallery:
        enabled: true
        blur: true
        image_width: 296
        image_per_page: 6
        show_buttons: true
        orientation: "portrait"
        image_spacing: 10
        lazy_load: true
        lazy_load_fadein: 200
        image_corner_radius: 20
  power_menu:
      type: "yasb.power_menu.PowerMenuWidget"
      options:
        label: "\uf011"
        uptime: True
        blur: False
        blur_background: True
        animation_duration: 250 # Milisecond 
        button_row: 5 # Number of buttons in row, min 1 max 5
        buttons:
          signout: ["\udb80\udf43","Sign out"]
          shutdown: ["\uf011","Shut Down"]
          restart: ["\uead2","Restart"]
          hibernate: ["\uf28e","Hibernate"]
          cancel: ["\udb81\udf3a","Cancel"]
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 12
      gradient: 0
      reverse: 0
      sensitivity: 100
      foreground: "#1a1b26"
      gradient_color_1: '#74c7ec'
      gradient_color_2: '#89b4fa'
      gradient_color_3: '#cba6f7'
      bars_number: 12
      bar_spacing: 2
      bar_width: 4
      sleep_timer: 0
      hide_empty: true
  github:
    type: "yasb.github.GithubWidget"
    options:
      label: "<span>\ueba1</span>"
      label_alt: "Notifications {data}" # {data} return number of unread notification
      token: env # GitHub Personal access tokens (classic) https://github.com/settings/tokens
      max_notification: 20 # Max number of notification displaying in menu max: 50
      only_unread: false # Show only unread or all notifications; 
      max_field_size: 54 # Max characters in title before truncation.
      update_interval: 300 # Check for new notification in seconds
      menu:
        blur: True # Enable blur effect for the menu
        round_corners: True # Enable round corners for the menu (this option is not supported on Windows 10)
        round_corners_type: "normal" # Set the type of round corners for the menu (normal, small) (this option is not supported on Windows 10)
        border_color: "System" # Set the border color for the menu (this option is not supported on Windows 10)
        alignment: "right"
        direction: "down"
        distance: 6
  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{layout_name}"
      layouts: ['bsp', 'columns', 'rows', 'grid', 'vertical_stack', 'horizontal_stack', 'ultrawide_vertical_stack','right_main_vertical_stack']
      layout_icons:
        bsp: "\uebeb"
        columns: "\uebf7"
        rows: "\uec01"
        grid: "\udb81\udf58"
        scrolling: "\uebf7"
        vertical_stack: "\uebee"
        horizontal_stack: "\uebf0"
        ultrawide_vertical_stack: "\uebee"
        right_main_vertical_stack: "\uebf1"
        monocle: "\uf06f"
        maximized: "\uf06f"
        floating: "\uf2d2"
        paused: "\udb83\udf89"
        tiling: "\udb81\ude40"
      callbacks:
        on_left: 'toggle_layout_menu'
        on_middle: 'next_layout'
        on_right: 'prev_layout'
      layout_menu:
        blur: false
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "left"
        direction: "down"
        offset_top: 5
        offset_left: 5
        show_layout_icons: true
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\ue8a9"
      label_expanded: "\ue76c"
      icon_size: 16
      show_unpinned: false
      show_unpinned_button: true
      show_battery: true
      show_volume: false
      show_network: false
  whkd:
    type: "yasb.whkd.WhkdWidget"
    options:
      label: "<span>\uf11c</span>"
      special_keys:
        - key: "win"
          key_replace: "Win"
        - key: "ctrl"
          key_replace: "Ctrl"
        - key: "alt"
          key_replace: "Alt"
        - key: "shift"
          key_replace: "Shift"
        - key: "left"
          key_replace: "←"
        - key: "right"
          key_replace: "→"
        - key: "up"
          key_replace: "↑"
        - key: "down"
          key_replace: "↓"

  update_check:
    type: "yasb.update_check.UpdateCheckWidget"
    options:
      windows_update:
        enabled: true
        label: "<span>\uf0ab</span> {count}"
        interval: 1440
        exclude: []
      winget_update:
        enabled: true
        label: "<span>\uf0ab</span> {count}"
        interval: 240
        exclude:
          - "Microsoft.Edge"
      scoop_update:
        enabled: false
        label: "<span>\uf0ab</span> {count}"
        interval: 240
        exclude: []

  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 16
      callbacks:
        on_left: "toggle_window"
        on_middle: "close_app"
        on_right: "context_menu"
      tooltip: true
      show_only_visible: false
      strict_filtering: true
      monitor_exclusive: true
      animation:
        enabled: true
        duration: 150
      preview:
        enabled: true
        width: 260
        delay: 200
        padding: 8
        margin: 8
      title_label:
        enabled: true
        show: "focused"
        min_length: 10
        max_length: 30
      ignore_apps:
        processes:
          - "SearchHost.exe"
          - "TextInputHost.exe"
        titles: []
        classes: []